# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlpacaFlashcards' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AlpacaFlashcards
  pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

  target 'AlpacaFlashcards-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlpacaFlashcardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AlpacaFlashcards-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AlpacaFlashcards-tvOS

  target 'AlpacaFlashcards-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
